"use client";

import { Button } from "@/components/ui/button";
import Link from "next/link";
import { useEffect, useState } from "react";
import { SignedIn, SignedOut, SignInButton } from "@clerk/nextjs";

const FEATURES = [
  {
    icon: "🤖",
    title: "AI-Powered Questions",
    description: "Generated by advanced AI tailored to your certification path and skill level"
  },
  {
    icon: "📊",
    title: "Real-Time Analytics",
    description: "Track your progress with detailed performance insights and improvement metrics"
  },
  {
    icon: "🎯",
    title: "Exam-Level Practice",
    description: "Practice questions matching real certification exam difficulty and patterns"
  },
  {
    icon: "☁️",
    title: "Multi-Cloud Support",
    description: "Prepare for AWS, Azure, GCP certifications across all levels"
  },
  {
    icon: "⚡",
    title: "Adaptive Learning",
    description: "Difficulty adjusts based on your performance for optimal learning"
  },
  {
    icon: "📱",
    title: "Learn Anywhere",
    description: "Fully responsive design works seamlessly on desktop, tablet, and mobile"
  }
];

const STATS = [
  { number: "10K+", label: "Active Learners" },
  { number: "85%", label: "First Attempt Pass Rate" },
  { number: "5000+", label: "Practice Questions" },
  { number: "24/7", label: "Expert Support" }
];

export default function Home() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50/30 via-indigo-50/20 to-purple-50/30 dark:from-slate-950 dark:via-slate-900 dark:to-indigo-950/20 overflow-hidden">
      {/* Hero Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid lg:grid-cols-2 gap-12 items-center min-h-[80vh]">
          {/* Left Content */}
          <div className={`space-y-8 transition-all duration-1000 ease-out ${
            isVisible ? 'opacity-100 translate-x-0' : 'opacity-0 -translate-x-12'
          }`}>
            <div className="space-y-6">
              <div className="inline-block px-4 py-2 bg-blue-100/50 dark:bg-blue-900/20 rounded-full border border-blue-200 dark:border-blue-800">
                <span className="text-sm font-semibold text-blue-700 dark:text-blue-400">✨ Master Cloud Certifications</span>
              </div>
              
              <h1 className={`text-5xl md:text-6xl lg:text-7xl font-bold leading-tight transition-all duration-1200 ease-out delay-200 ${
                isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
              }`}>
                <span className="bg-gradient-to-r from-blue-600/90 to-purple-600/90 bg-clip-text text-transparent animate-gradient">
                  Ace Your Cloud
                </span>
                <br />
                <span className="text-foreground">
                  Certification Exams
                </span>
              </h1>
              
              <p className={`text-lg md:text-xl text-muted-foreground max-w-2xl leading-relaxed transition-all duration-1000 ease-out delay-400 ${
                isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
              }`}>
                Join thousands of professionals who've successfully passed their AWS, Azure, and GCP certifications using our intelligent quiz platform with real-time analytics and adaptive learning.
              </p>
            </div>

            {/* Stats */}
            <div className={`grid grid-cols-2 gap-4 transition-all duration-1000 ease-out delay-500 ${
              isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
            }`}>
              {STATS.map((stat, index) => (
                <div key={index} className="bg-white/50 dark:bg-slate-800/50 rounded-lg p-4 border border-gray-200/50 dark:border-slate-700/50 backdrop-blur-sm">
                  <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">{stat.number}</div>
                  <div className="text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </div>
            
            {/* Action Buttons */}
            <div className={`flex flex-col sm:flex-row gap-4 transition-all duration-1000 ease-out delay-700 ${
              isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
            }`}>
              <SignedIn>
                <Link href="/quiz-setup">
                  <Button 
                    size="lg"
                    className="bg-gradient-to-r from-blue-600/90 to-purple-600/90 hover:from-blue-700/90 hover:to-purple-700/90 text-white px-8 py-4 text-lg font-semibold transition-all duration-300 transform hover:scale-105 hover:shadow-lg hover:shadow-blue-500/20 w-full sm:w-auto"
                  >
                    🚀 Start Quiz Now
                  </Button>
                </Link>
              </SignedIn>
              
              <SignedOut>
                <SignInButton>
                  <Button 
                    size="lg"
                    className="bg-gradient-to-r from-blue-600/90 to-purple-600/90 hover:from-blue-700/90 hover:to-purple-700/90 text-white px-8 py-4 text-lg font-semibold transition-all duration-300 transform hover:scale-105 hover:shadow-lg hover:shadow-blue-500/20 w-full sm:w-auto"
                  >
                    🔐 Sign in & Start
                  </Button>
                </SignInButton>
              </SignedOut>

              <Link href="/free-test">
                <Button 
                  variant="outline" 
                  size="lg"
                  className="border-2 border-emerald-600 dark:border-emerald-400 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-900/20 px-8 py-4 text-lg font-semibold transition-all duration-300 w-full sm:w-auto"
                >
                  🎯 Try Free Demo
                </Button>
              </Link>
              
              <Link href="/contact">
                <Button 
                  variant="outline" 
                  size="lg"
                  className="border-2 border-blue-600 dark:border-blue-400 text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20 px-8 py-4 text-lg font-semibold transition-all duration-300 w-full sm:w-auto"
                >
                  💬 Get Support
                </Button>
              </Link>
            </div>
          </div>

          {/* Right Content - Illustration */}
          <div className={`relative items-center justify-center transition-all duration-1200 ease-out delay-300 hidden lg:flex ${
            isVisible ? 'opacity-100 translate-x-0 rotate-0' : 'opacity-0 translate-x-12 rotate-12'
          }`}>
            <div className="relative w-96 h-96">
              {/* Main Card */}
              <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-purple-500/20 rounded-2xl border border-white/20 backdrop-blur-xl shadow-2xl p-8 flex flex-col justify-between">
                <div className="space-y-4">
                  <div className="text-4xl">🎓</div>
                  <h3 className="text-2xl font-bold text-foreground">Ready to Level Up?</h3>
                  <p className="text-sm text-muted-foreground">Start your certification journey with interactive AI-powered quizzes</p>
                </div>
                <div className="flex gap-2">
                  <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></div>
                  <div className="w-2 h-2 rounded-full bg-purple-500 animate-pulse animation-delay-200"></div>
                  <div className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse animation-delay-400"></div>
                </div>
              </div>

              {/* Floating Cards */}
              <div className="absolute -top-8 -right-8 w-32 h-32 bg-gradient-to-br from-blue-400 to-blue-500 rounded-xl shadow-lg p-4 text-white transform hover:scale-110 transition-transform duration-300 flex flex-col justify-center items-center text-center animate-bounce">
                <div className="text-3xl mb-2">📈</div>
                <div className="text-xs font-semibold">Track Progress</div>
              </div>

              <div className="absolute -bottom-6 -left-6 w-32 h-32 bg-gradient-to-br from-purple-400 to-purple-500 rounded-xl shadow-lg p-4 text-white transform hover:scale-110 transition-transform duration-300 flex flex-col justify-center items-center text-center animate-bounce" style={{ animationDelay: '0.5s' }}>
                <div className="text-3xl mb-2">🎯</div>
                <div className="text-xs font-semibold">Expert Tips</div>
              </div>

              <div className="absolute top-1/3 -right-12 w-28 h-28 bg-gradient-to-br from-indigo-400 to-indigo-500 rounded-xl shadow-lg p-3 text-white transform hover:scale-110 transition-transform duration-300 flex flex-col justify-center items-center text-center animate-pulse">
                <div className="text-2xl mb-1">⚡</div>
                <div className="text-xs font-semibold">Learn Fast</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <section className="py-20 bg-white/50 dark:bg-slate-800/30 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16 animate-fade-in-up">
            <h2 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-blue-600/90 to-purple-600/90 bg-clip-text text-transparent">
              Why Choose Our Platform?
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Everything you need to succeed in your cloud certification journey
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {FEATURES.map((feature, index) => (
              <div 
                key={index}
                className="bg-white dark:bg-slate-800 rounded-xl p-8 border border-gray-200 dark:border-slate-700 shadow-sm hover:shadow-lg transition-all duration-300 animate-fade-in-up cursor-pointer group hover:border-blue-500 dark:hover:border-blue-400"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="text-4xl mb-4 group-hover:scale-110 transition-transform duration-300">{feature.icon}</div>
                <h3 className="text-xl font-semibold mb-3 text-foreground group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">{feature.title}</h3>
                <p className="text-muted-foreground leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-gradient-to-r from-blue-50/40 to-purple-50/40 dark:from-slate-900/40 dark:to-slate-800/40 rounded-2xl p-12 border border-blue-200/20 dark:border-slate-700/20 text-center backdrop-blur-sm animate-fade-in">
            <h3 className="text-3xl md:text-4xl font-bold mb-6 text-foreground">
              Start Your Certification Journey Today
            </h3>
            <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
              Join thousands of professionals who've passed their cloud certifications with our proven platform. Free forever core features available to all users.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <SignedIn>
                <Link href="/quiz-setup">
                  <Button 
                    size="lg"
                    className="bg-gradient-to-r from-blue-600/90 to-purple-600/90 hover:from-blue-700/90 hover:to-purple-700/90 text-white px-10 py-4 text-lg font-semibold transition-all duration-300 transform hover:scale-105 hover:shadow-lg"
                  >
                    Start Quiz
                  </Button>
                </Link>
              </SignedIn>
              
              <SignedOut>
                <SignInButton>
                  <Button 
                    size="lg"
                    className="bg-gradient-to-r from-blue-600/90 to-purple-600/90 hover:from-blue-700/90 hover:to-purple-700/90 text-white px-10 py-4 text-lg font-semibold transition-all duration-300 transform hover:scale-105 hover:shadow-lg"
                  >
                    Get Started Free
                  </Button>
                </SignInButton>
              </SignedOut>

              <Link href="/exam-syllabus">
                <Button 
                  variant="outline" 
                  size="lg"
                  className="border-2 border-blue-600 dark:border-blue-400 text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20 px-10 py-4 text-lg font-semibold transition-all duration-300"
                >
                  Browse Certifications
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Background decorative elements */}
      <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 rounded-full bg-blue-200/10 dark:bg-blue-800/10 blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 rounded-full bg-purple-200/10 dark:bg-purple-800/10 blur-3xl animate-pulse animation-delay-500"></div>
        <div className="absolute top-1/2 right-1/3 w-80 h-80 rounded-full bg-indigo-200/10 dark:bg-indigo-800/10 blur-3xl animate-pulse animation-delay-1000"></div>
      </div>
    </main>
  );
}
